CREATE TABLE IF NOT EXISTS user
(
    id            VARCHAR(255) PRIMARY KEY,
    password      VARCHAR(255) NOT NULL,
    high_score    INT NOT NULL DEFAULT 0,
    last_login    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS error_logs 
(
    id            INT AUTO_INCREMENT PRIMARY KEY,
    user_id       VARCHAR(255) NOT NULL,
    log_content   TEXT NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
